# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aihub < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/NSXBet/aihubcode"
  version "7.4.25"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NSXBet/aihubcode/releases/download/v7.4.25/aihub-darwin-x64.zip"
      sha256 "1a789973cf7fe91c7723561810d666f316b4669fb3f76acfbf4ee2331820fbf3"

      def install
        libexec.install "aihub", "aihub-sandbox-mutation-worker.js", "tree-sitter"
        (bin/"aihub").write_env_script libexec/"aihub", AIHUB_TREE_SITTER_WASM_DIR: libexec/"tree-sitter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NSXBet/aihubcode/releases/download/v7.4.25/aihub-darwin-arm64.zip"
      sha256 "e05512d464aacf4db66d81fc065afc23b277303a97576cb55f2e5148666e8eb2"

      def install
        libexec.install "aihub", "aihub-sandbox-mutation-worker.js", "tree-sitter"
        (bin/"aihub").write_env_script libexec/"aihub", AIHUB_TREE_SITTER_WASM_DIR: libexec/"tree-sitter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/NSXBet/aihubcode/releases/download/v7.4.25/aihub-linux-x64.tar.gz"
      sha256 "4470d4cb78f7128e81855964aab761a201c27766cd3b43292056f2b1352c7572"
      def install
        libexec.install "aihub", "bwrap", "aihub-sandbox-mutation-worker.js", "tree-sitter", "licenses"
        (bin/"aihub").write_env_script libexec/"aihub", AIHUB_TREE_SITTER_WASM_DIR: libexec/"tree-sitter"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/NSXBet/aihubcode/releases/download/v7.4.25/aihub-linux-arm64.tar.gz"
      sha256 "47601550a87db8df8b36d4ba54546e69740990d3872d59222d477e83a3a2ce58"
      def install
        libexec.install "aihub", "bwrap", "aihub-sandbox-mutation-worker.js", "tree-sitter", "licenses"
        (bin/"aihub").write_env_script libexec/"aihub", AIHUB_TREE_SITTER_WASM_DIR: libexec/"tree-sitter"
      end
    end
  end
end

