# This file was generated by GoReleaser. DO NOT EDIT.
cask "graphify-test-runner" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "b91a0b3c4e9bfc8e8fccc4d0babf7c50f3cc309c781ec8012daa03e06819b4d0"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f33b2c3b4a617781e35e8ff42af5457b88abce6691f3d60e14ebbce579acbe34"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "61184b0a7daf5832dc9fda5d31e72c1a9aba363a94a29bd41217ec475a45d07b"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8997469df1c04385ebc0d039365e036e1d520e7802f2dc411d00511ab7fc85e8"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_linux_amd64.tar.gz"
    end
  end

  name "graphify-test-runner"
  desc "Select and run only the Go tests a change can affect"
  homepage "https://github.com/NSXBet/go-graphify-test-runner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graphify-test-runner"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/graphify-test-runner"]
    end
  end

  # No zap stanza required
end
