# This file was generated by GoReleaser. DO NOT EDIT.
cask "graphify-test-runner" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "4a815a7a83770b1984c94f3ae9b6b63128fe1817902e2a257c24694e0e2c58c4"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c09e2eb3df08d9ae0d9ddd0550c33a6e98ec3d8811b50ecf6c1b0613756b2a01"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "96aa90c5246ed8595022637a45c08a3ef143803a6aa446c010c1c9215acc15d0"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a33b66e328b7ab6100444eeffce9dd7261c922f5580fee1827c013e34ac20d37"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_linux_amd64.tar.gz"
    end
  end

  name "graphify-test-runner"
  desc "Select and run only the Go tests a change can affect"
  homepage "https://github.com/NSXBet/go-graphify-test-runner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graphify-test-runner"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/graphify-test-runner"]
    end
  end

  # No zap stanza required
end
