# This file was generated by GoReleaser. DO NOT EDIT.
cask "graphify-test-runner" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "e53f49c60f0e5cf77cc62f5cf95de6c56e385ed969c7467789d3d9a25b71ee7f"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f801d431488c2c026e61eddb004db23cbc3e120eb5f3ac190375489a761573b1"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a40cfbbae195b8074381153d40edebe301e67b4e0a41897d1ad9a2145f69a937"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc37015c58194d41de8510e18b92dadabd5335194801b10d79ada830b7fbb897"
      url "https://github.com/NSXBet/go-graphify-test-runner/releases/download/v#{version}/graphify-test-runner_#{version}_linux_amd64.tar.gz"
    end
  end

  name "graphify-test-runner"
  desc "Select and run only the Go tests a change can affect"
  homepage "https://github.com/NSXBet/go-graphify-test-runner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graphify-test-runner"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/graphify-test-runner"]
    end
  end

  # No zap stanza required
end
