# This file was generated by GoReleaser. DO NOT EDIT.
cask "smart-test-runner" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "efc1947ab4d080e4d66c1841642ae4c0611b20b003bad8e5d7d95088380f3af3"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "71d778ba8daad14ee0400cc654f0d5c326c8673d10d4c78e0f8895e20b5a209c"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6bd48a3301132bafb195e695b5cebb4004326a00c472347cb2074fe094a782ac"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6a7568f4f1ae307e2591e995b6f58d3f90df11e1e17dcac56c1ef8e0641e85b8"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_linux_amd64.tar.gz"
    end
  end

  name "smart-test-runner"
  desc "Select and run only the Go tests a change can affect"
  homepage "https://github.com/NSXBet/go-smart-test-runner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smart-test-runner"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smart-test-runner"]
    end
  end

  # No zap stanza required
end
