# This file was generated by GoReleaser. DO NOT EDIT.
cask "smart-test-runner" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "6be99afca8afae22d96cfb24b5df6e91ac5ba12b07a8ba1746bf08911ae840d5"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a741f6f18b679f062658d364f6dd0d3cc9dfb23a89df6c30e4b3a6069ea04e6e"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fddf5318bf7c5e072eb27694a124b0830f15e0257befd0d774ea60b92883b0d2"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6158fd1b46ff6abe967e81764eba559c95c91caf9e764a74ad7d2ed491bb64ff"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_linux_amd64.tar.gz"
    end
  end

  name "smart-test-runner"
  desc "Select and run only the Go tests a change can affect"
  homepage "https://github.com/NSXBet/go-smart-test-runner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smart-test-runner"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smart-test-runner"]
    end
  end

  # No zap stanza required
end
