# This file was generated by GoReleaser. DO NOT EDIT.
cask "smart-test-runner" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "0b5e8345cbcb065b0d773f808ee54bb64f8ffea6c15b33e7df5617d32e3db76d"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e5cc88f8531c3d32af220cd95a3ac953a39a39f71dc6792058b7a19d8715f3fa"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf93e18aca32b1493d13883ae8e2bd918ad7d880bc4712b6b39fc4d4dc9ecb25"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5ff7c984481e88772fde159f5ef8a0ba7921840f8a444d8a36acf93def9003c"
      url "https://github.com/NSXBet/go-smart-test-runner/releases/download/v#{version}/smart-test-runner_#{version}_linux_amd64.tar.gz"
    end
  end

  name "smart-test-runner"
  desc "Select and run only the Go tests a change can affect"
  homepage "https://github.com/NSXBet/go-smart-test-runner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smart-test-runner"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smart-test-runner"]
    end
  end

  # No zap stanza required
end
