# frozen_string_literal: true

# Generated by NSXBet/homebrew-tap scripts/generate-formula.sh — DO NOT EDIT.
class TiltDev < Formula
  desc "Tilt (NSXBet fork) — Kubernetes dev environment as code"
  homepage "https://github.com/NSXBet/tilt"
  version "0.37.7-nsx.1"

  on_macos do
    on_arm do
      url "https://github.com/NSXBet/tilt/releases/download/v0.37.7-nsx.1/tilt.0.37.7-nsx.1.mac.arm64.tar.gz"
      sha256 "31f0043f0f2159f5a409af23b28acfebd91da335eed054443aed2494ea5e0ade"
    end
    on_intel do
      url "https://github.com/NSXBet/tilt/releases/download/v0.37.7-nsx.1/tilt.0.37.7-nsx.1.mac.x86_64.tar.gz"
      sha256 "f7fec0136b8a2cec35e2b1a2c7a3e7c3df6aead458eb7af23587fa53f3b9b752"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/NSXBet/tilt/releases/download/v0.37.7-nsx.1/tilt.0.37.7-nsx.1.linux.arm64.tar.gz"
      sha256 "323e7d3494c45347523323b9070972cfe055bb588d4fd1ba956a79fa9ff0a4ce"
    end
    on_intel do
      url "https://github.com/NSXBet/tilt/releases/download/v0.37.7-nsx.1/tilt.0.37.7-nsx.1.linux.x86_64.tar.gz"
      sha256 "b350692365371acfc982075964e655732af2ea969e98373a36469ff95dd31dfd"
    end
  end

  def install
    bin.install "tilt"
    (bash_completion/"tilt").write Utils.safe_popen_read("#{bin}/tilt", "completion", "bash")
    (zsh_completion/"tilt").write Utils.safe_popen_read("#{bin}/tilt", "completion", "zsh")
    (fish_completion/"tilt.fish").write Utils.safe_popen_read("#{bin}/tilt", "completion", "fish")
  end

  test do
    system "#{bin}/tilt", "version"
  end
end
