# frozen_string_literal: true

# Generated by NSXBet/homebrew-tap scripts/generate-formula.sh — DO NOT EDIT.
class Tip < Formula
  desc "Tilt (NSXBet fork) — Kubernetes dev environment as code"
  homepage "https://github.com/NSXBet/tilt"
  version "tip-20260919-954dfed"

  on_macos do
    on_arm do
      url "https://github.com/NSXBet/tilt/releases/download/tip/tilt.tip-20260919-954dfed.mac.arm64.tar.gz"
      sha256 "9c5f75b7bd84e889a4ba43f7afecf2c9ffd74605357f5536a0b79ef4c5611eb1"
    end
    on_intel do
      url "https://github.com/NSXBet/tilt/releases/download/tip/tilt.tip-20260919-954dfed.mac.x86_64.tar.gz"
      sha256 "3fb9a4ea89fa5749976819e8bb1aaf01193f2880cfe3751ceb752b37ed23275c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/NSXBet/tilt/releases/download/tip/tilt.tip-20260919-954dfed.linux.arm64.tar.gz"
      sha256 "eb72eba68e00baf3b6b59df23f798de0fa7ccab6962341259bf9751a951d4589"
    end
    on_intel do
      url "https://github.com/NSXBet/tilt/releases/download/tip/tilt.tip-20260919-954dfed.linux.x86_64.tar.gz"
      sha256 "8c1bc32714176f818248c26dd50d3989029c3c32f21cb858f2cc30e69220360c"
    end
  end

  def install
    bin.install "tilt" => "tip"
  end

  test do
    system "#{bin}/tip", "version"
  end
end
