#!/bin/bash
#
# Render a Homebrew formula for an NSXBet/tilt release.
#
# Usage:
#   scripts/generate-formula.sh --name tilt-dev --version 0.35.1 \
#     --tag v0.35.1 --binary tilt --checksums dist/checksums.txt [--keg-only]
#
# Prints the formula to stdout. Archive names must match the release pipeline
# in NSXBet/tilt (.github/workflows/fork-release.yml):
#   tilt.<version>.mac.arm64.tar.gz
#   tilt.<version>.mac.x86_64.tar.gz
#   tilt.<version>.linux.arm64.tar.gz
#   tilt.<version>.linux.x86_64.tar.gz

set -euo pipefail

NAME="" VERSION="" TAG="" BINARY="tilt" KEG_ONLY=0 CHECKSUMS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) NAME="$2"; shift 2 ;;
    --version) VERSION="$2"; shift 2 ;;
    --tag) TAG="$2"; shift 2 ;;
    --binary) BINARY="$2"; shift 2 ;;
    --checksums) CHECKSUMS="$2"; shift 2 ;;
    --keg-only) KEG_ONLY=1; shift ;;
    *) echo "unknown flag: $1" >&2; exit 1 ;;
  esac
done

for req in NAME VERSION TAG CHECKSUMS; do
  [[ -n "${!req}" ]] || { echo "missing --$(echo "$req" | tr '[:upper:]' '[:lower:]')" >&2; exit 1; }
done
[[ -f "$CHECKSUMS" ]] || { echo "checksums file not found: $CHECKSUMS" >&2; exit 1; }

sha_for() {
  awk -v f="$1" '$2 == f { print $1; found=1 } END { if (!found) exit 1 }' "$CHECKSUMS"
}

SHA_MAC_ARM64=$(sha_for "tilt.${VERSION}.mac.arm64.tar.gz")
SHA_MAC_X86=$(sha_for "tilt.${VERSION}.mac.x86_64.tar.gz")
SHA_LINUX_ARM64=$(sha_for "tilt.${VERSION}.linux.arm64.tar.gz")
SHA_LINUX_X86=$(sha_for "tilt.${VERSION}.linux.x86_64.tar.gz")

BASE_URL="https://github.com/NSXBet/tilt/releases/download/${TAG}"

# Homebrew class name: tilt-dev@0.35.1 -> TiltDevAT0351, tip -> Tip
cap() { printf '%s%s' "$(printf '%s' "${1:0:1}" | tr '[:lower:]' '[:upper:]')" "${1:1}"; }
stem="${NAME%%@*}"
CLASS=""
IFS='-' read -ra SEGMENTS <<< "$stem"
for seg in "${SEGMENTS[@]}"; do
  CLASS+="$(cap "$seg")"
done
if [[ "$NAME" == *"@"* ]]; then
  digits="${NAME#*@}"
  digits="${digits//[^0-9]/}"
  CLASS+="AT${digits}"
fi

KEG_ONLY_LINE=""
if [[ "$KEG_ONLY" -eq 1 ]]; then
  KEG_ONLY_LINE="  keg_only :versioned_formula"
fi

if [[ "$BINARY" == "tilt" ]]; then
  BIN_INSTALL='    bin.install "tilt"'
else
  BIN_INSTALL='    bin.install "tilt" => "'"${BINARY}"'"'
fi

COMPLETIONS=""
if [[ "$BINARY" == "tilt" ]]; then
  COMPLETIONS='
    (bash_completion/"tilt").write Utils.safe_popen_read("#{bin}/tilt", "completion", "bash")
    (zsh_completion/"tilt").write Utils.safe_popen_read("#{bin}/tilt", "completion", "zsh")
    (fish_completion/"tilt.fish").write Utils.safe_popen_read("#{bin}/tilt", "completion", "fish")'
fi

cat <<EOF | awk 'BEGIN { blank=0 } /^[[:space:]]*$/ { blank++; if (blank > 1) next } !/^[[:space:]]*$/ { blank=0 } { print }'
# frozen_string_literal: true

# Generated by NSXBet/homebrew-tap scripts/generate-formula.sh — DO NOT EDIT.
class ${CLASS} < Formula
  desc "Tilt (NSXBet fork) — Kubernetes dev environment as code"
  homepage "https://github.com/NSXBet/tilt"
  version "${VERSION}"

  on_macos do
    on_arm do
      url "${BASE_URL}/tilt.${VERSION}.mac.arm64.tar.gz"
      sha256 "${SHA_MAC_ARM64}"
    end
    on_intel do
      url "${BASE_URL}/tilt.${VERSION}.mac.x86_64.tar.gz"
      sha256 "${SHA_MAC_X86}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/tilt.${VERSION}.linux.arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end
    on_intel do
      url "${BASE_URL}/tilt.${VERSION}.linux.x86_64.tar.gz"
      sha256 "${SHA_LINUX_X86}"
    end
  end

${KEG_ONLY_LINE}

  def install
${BIN_INSTALL}${COMPLETIONS}
  end

  test do
    system "#{bin}/${BINARY}", "version"
  end
end
EOF
